controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_hello_routes:
#     path: /hello
#     controller: App\Controller\HelloController::hello